
package Telas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


public class ConsultaDados extends javax.swing.JFrame {
 
    static String cpf = "";
    
    public ConsultaDados(String cpf) {
        initComponents();
         preencherCampos(cpf);
    }
     private void preencherCampos(String cpf) {
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;
       // puxa os dados do respcetivo usuário
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            String url = "jdbc:mysql://localhost:3306/fatecparking";
            String usuario = "root";
            String senha = "";
            connection = DriverManager.getConnection(url, usuario, senha);
          
            statement = connection.createStatement();

            String consultaSQL = "SELECT * FROM informacoes WHERE cpf = '" + cpf+ "'";
                  
            resultSet = statement.executeQuery(consultaSQL);

            if (resultSet.next()) {
                conNome.setText(resultSet.getString("nome"));
                conCpf.setText(resultSet.getString("cpf"));
                conRa.setText(resultSet.getString("ra"));

                conEmail.setText(resultSet.getString("email"));
                conTelefone.setText(resultSet.getString("telefone"));
                conSenha.setText(resultSet.getString("senha"));
                conCurso.setText(resultSet.getString("curso"));
                conFuncao.setText(resultSet.getString("funcao"));

                conMarca.setText(resultSet.getString("marcaveiculo"));
                conModelo.setText(resultSet.getString("modeloveiculo"));
                conPlaca.setText(resultSet.getString("placaveiculo"));
                conCor.setText(resultSet.getString("corveiculo"));
                conVaga.setText(resultSet.getString("vaga"));
            }
            
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        } finally {
            try {
                if (resultSet != null) {
                    resultSet.close();
                }
                if (statement != null) {
                    statement.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Consultar = new javax.swing.JLabel();
        Ra = new javax.swing.JLabel();
        conNome = new javax.swing.JTextField();
        Cpf = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        Funcao = new javax.swing.JLabel();
        Curso = new javax.swing.JLabel();
        ModeloVeiculo = new javax.swing.JLabel();
        PlacaVeiculo = new javax.swing.JLabel();
        Vaga = new javax.swing.JLabel();
        MarcaVeiculo = new javax.swing.JLabel();
        CorVeiculo = new javax.swing.JLabel();
        conRa = new javax.swing.JTextField();
        conEmail = new javax.swing.JTextField();
        conCor = new javax.swing.JTextField();
        conCpf = new javax.swing.JTextField();
        conTelefone = new javax.swing.JTextField();
        conSenha = new javax.swing.JTextField();
        conCurso = new javax.swing.JTextField();
        conFuncao = new javax.swing.JTextField();
        conMarca = new javax.swing.JTextField();
        conModelo = new javax.swing.JTextField();
        conPlaca = new javax.swing.JTextField();
        conVaga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Dados");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(3, 1, 57));

        Consultar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Consultar.setForeground(new java.awt.Color(255, 255, 255));
        Consultar.setText("Consultar Dados");

        Ra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ra.setForeground(new java.awt.Color(255, 255, 255));
        Ra.setText("RA");

        conNome.setEditable(false);

        Cpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cpf.setForeground(new java.awt.Color(255, 255, 255));
        Cpf.setText("CPF");

        Nome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nome.setForeground(new java.awt.Color(255, 255, 255));
        Nome.setText("Nome");

        Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email");

        Telefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Telefone.setForeground(new java.awt.Color(255, 255, 255));
        Telefone.setText("Telefone");

        Senha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Senha.setForeground(new java.awt.Color(255, 255, 255));
        Senha.setText("Senha");

        Funcao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Funcao.setForeground(new java.awt.Color(255, 255, 255));
        Funcao.setText("Função");

        Curso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Curso.setForeground(new java.awt.Color(255, 255, 255));
        Curso.setText("Curso");

        ModeloVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ModeloVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        ModeloVeiculo.setText("Modelo do Veículo");

        PlacaVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PlacaVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        PlacaVeiculo.setText("Placa do Veículo");

        Vaga.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Vaga.setForeground(new java.awt.Color(255, 255, 255));
        Vaga.setText("Vaga");

        MarcaVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MarcaVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        MarcaVeiculo.setText("Marca do Veículo");

        CorVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CorVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        CorVeiculo.setText("Cor do Veículo");

        conRa.setEditable(false);

        conEmail.setEditable(false);

        conCor.setEditable(false);

        conCpf.setEditable(false);

        conTelefone.setEditable(false);

        conSenha.setEditable(false);

        conCurso.setEditable(false);

        conFuncao.setEditable(false);

        conMarca.setEditable(false);

        conModelo.setEditable(false);

        conPlaca.setEditable(false);

        conVaga.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(Consultar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Curso)
                                            .addComponent(Senha))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(conSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(conCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Cpf)
                                            .addComponent(Ra)
                                            .addComponent(Email)
                                            .addComponent(Telefone))
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(conCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(conRa, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(conEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(conTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PlacaVeiculo)
                                            .addComponent(ModeloVeiculo)
                                            .addComponent(MarcaVeiculo)
                                            .addComponent(CorVeiculo)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Vaga)
                                                .addGap(18, 18, 18)
                                                .addComponent(conVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(conModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(conMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(conPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(conCor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Nome)
                                .addGap(26, 26, 26)
                                .addComponent(conNome, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(Funcao)
                                .addGap(19, 19, 19)
                                .addComponent(conFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Consultar)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ra)
                            .addComponent(conRa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cpf)
                            .addComponent(conCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MarcaVeiculo)
                            .addComponent(conMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModeloVeiculo)
                            .addComponent(conModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Email))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PlacaVeiculo)
                                    .addComponent(conPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CorVeiculo)
                            .addComponent(conCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Vaga)
                            .addComponent(conVaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(conEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(conCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Telefone)
                                    .addComponent(conTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Senha)
                                    .addComponent(conSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(Curso)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Funcao)
                            .addComponent(conFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaDados(cpf).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Consultar;
    private javax.swing.JLabel CorVeiculo;
    private javax.swing.JLabel Cpf;
    private javax.swing.JLabel Curso;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Funcao;
    private javax.swing.JLabel MarcaVeiculo;
    private javax.swing.JLabel ModeloVeiculo;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel PlacaVeiculo;
    private javax.swing.JLabel Ra;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel Telefone;
    private javax.swing.JLabel Vaga;
    private javax.swing.JTextField conCor;
    private javax.swing.JTextField conCpf;
    private javax.swing.JTextField conCurso;
    private javax.swing.JTextField conEmail;
    private javax.swing.JTextField conFuncao;
    private javax.swing.JTextField conMarca;
    private javax.swing.JTextField conModelo;
    private javax.swing.JTextField conNome;
    private javax.swing.JTextField conPlaca;
    private javax.swing.JTextField conRa;
    private javax.swing.JTextField conSenha;
    private javax.swing.JTextField conTelefone;
    private javax.swing.JTextField conVaga;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    
}
